In [1]:
import sys, os
import numpy as np
from pprint import pprint
import time
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

ruta_libs = os.path.abspath("../../libs")
if ruta_libs not in sys.path:
    sys.path.append(ruta_libs)

from networkLibs import *
from configUnits import *
from commonLibs import _mwMix_,_rhoMix_,_muMix_,_cpMix_,_kMix_,_propGas_,_set_propertyTable_,_get_propertyTable_,_get_propertieMixture_

In [2]:
adsColumn_1._initialize_()

In [3]:
adsColumn_1._state_cell_vars

{'t': 0.0,
 'N': array([4.0872058, 4.0872058, 4.0872058, 4.0872058, 4.0872058, 4.0872058,
        4.0872058, 4.0872058, 4.0872058, 4.0872058]),
 'v': array([0.00145683, 0.00145683, 0.00145683, 0.00145683, 0.00145683,
        0.00145683, 0.00145683, 0.00145683, 0.00145683, 0.00145683]),
 'P': array([350000., 350000., 350000., 350000., 350000., 350000., 350000.,
        350000., 350000., 350000.]),
 'Tg': array([298., 298., 298., 298., 298., 298., 298., 298., 298., 298.]),
 'Ts': array([298., 298., 298., 298., 298., 298., 298., 298., 298., 298.]),
 'x': array([0.55, 0.25, 0.15, 0.05, 0.55, 0.25, 0.15, 0.05, 0.55, 0.25, 0.15,
        0.05, 0.55, 0.25, 0.15, 0.05, 0.55, 0.25, 0.15, 0.05, 0.55, 0.25,
        0.15, 0.05, 0.55, 0.25, 0.15, 0.05, 0.55, 0.25, 0.15, 0.05, 0.55,
        0.25, 0.15, 0.05, 0.55, 0.25, 0.15, 0.05]),
 'q': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.00218413, 0.        ,
        0.        , 0.      

In [4]:
nodos=adsColumn_1._nodos
ncomp=adsColumn_1._ncomp
x=adsColumn_1._state_cell_vars['x'].reshape(nodos,ncomp)
T=adsColumn_1._state_cell_vars['Tg']
P=adsColumn_1._state_cell_vars['P']
species=adsColumn_1._species
MW=adsColumn_1._MW
mu=adsColumn_1._mu
k=adsColumn_1._K
cpg=adsColumn_1._cpg
cpg2=adsColumn_1._cpg2
sigma_A = adsColumn_1._sigmaLJ
epskB_A=adsColumn_1._epskB
T_range = adsColumn_1._T_range
P_range = adsColumn_1._P_range
data = adsColumn_1._prop_table
summary =  adsColumn_1._prop_summary

In [5]:
t0 = time.time()
MW1  = _mwMix_(x, MW)                 # [n]
rho1    = _rhoMix_(P, T, MW1)                    # [n]
mu1     = _muMix_(x, mu, MW)       # [n]
cp_molar1   = _cpMix_(x, cpg)                # molar 
cp_mass1     = _cpMix_(x, cpg2)               # MASA 
k1      = _kMix_(x, k, MW)      
t1 = time.time()
print(f"Tiempo de ejecución: {t1 - t0:.4f} segundos")

t0 = time.time()
MW2,rho2,mu2,cp2,k2=_propGas_(P,T,x,species)
t1 = time.time()
print(f"Tiempo de ejecución: {t1 - t0:.4f} segundos")

t0 = time.time()
MW3  = _mwMix_(x, MW)                 # [n]
rho3 = _get_propertieMixture_(data, summary, species, 'rho', T, P, x, T_range, P_range)
mu3 = _get_propertieMixture_(data, summary, species, 'mu', T, P, x, T_range, P_range)
cp3 = _get_propertieMixture_(data, summary, species, 'Cp', T, P, x, T_range, P_range)
k3  = _get_propertieMixture_(data, summary, species, 'k', T, P, x, T_range, P_range)
t1 = time.time()
print(f"Tiempo de ejecución: {t1 - t0:.4f} segundos")


Tiempo de ejecución: 0.0025 segundos
Tiempo de ejecución: 0.4843 segundos
Tiempo de ejecución: 0.1270 segundos


In [6]:
rho1,rho2,rho3

(array([5.28459637, 5.28459637, 5.28459637, 5.28459637, 5.28459637,
        5.28459637, 5.28459637, 5.28459637, 5.28459637, 5.28459637]),
 array([6.96779957, 6.96779957, 6.96779957, 6.96779957, 6.96779957,
        6.96779957, 6.96779957, 6.96779957, 6.96779957, 6.96779957]),
 array([7.21474166, 7.21474166, 7.21474166, 7.21474166, 7.21474166,
        7.21474166, 7.21474166, 7.21474166, 7.21474166, 7.21474166]))

In [7]:
mu1,mu2,mu3

(array([1.52629724e-05, 1.52629724e-05, 1.52629724e-05, 1.52629724e-05,
        1.52629724e-05, 1.52629724e-05, 1.52629724e-05, 1.52629724e-05,
        1.52629724e-05, 1.52629724e-05]),
 array([1.59882635e-05, 1.59882635e-05, 1.59882635e-05, 1.59882635e-05,
        1.59882635e-05, 1.59882635e-05, 1.59882635e-05, 1.59882635e-05,
        1.59882635e-05, 1.59882635e-05]),
 array([4.08259797e-05, 4.08259797e-05, 4.08259797e-05, 4.08259797e-05,
        4.08259797e-05, 4.08259797e-05, 4.08259797e-05, 4.08259797e-05,
        4.08259797e-05, 4.08259797e-05]))

In [8]:
cp_mass1,cp2,cp3

(array([912.687, 912.687, 912.687, 912.687, 912.687, 912.687, 912.687,
        912.687, 912.687, 912.687]),
 array([883.59270551, 883.59270551, 883.59270551, 883.59270551,
        883.59270551, 883.59270551, 883.59270551, 883.59270551,
        883.59270551, 883.59270551]),
 array([1190.18411015, 1190.18411015, 1190.18411015, 1190.18411015,
        1190.18411015, 1190.18411015, 1190.18411015, 1190.18411015,
        1190.18411015, 1190.18411015]))

In [9]:
k1,k2,k3

(array([0.01806882, 0.01806882, 0.01806882, 0.01806882, 0.01806882,
        0.01806882, 0.01806882, 0.01806882, 0.01806882, 0.01806882]),
 array([0.01866655, 0.01866655, 0.01866655, 0.01866655, 0.01866655,
        0.01866655, 0.01866655, 0.01866655, 0.01866655, 0.01866655]),
 array([0.03303063, 0.03303063, 0.03303063, 0.03303063, 0.03303063,
        0.03303063, 0.03303063, 0.03303063, 0.03303063, 0.03303063]))

In [ ]:

x

In [ ]:
species

In [12]:
data

{'CO2': {'rho': {'behavior': 'NoConstant',
   'const_val': None,
   'table': array([[1.79428007e-04, 7.55503344e+00, 1.51098875e+01, 2.26647415e+01,
           3.02195955e+01, 3.77744495e+01, 4.53293035e+01, 5.28841575e+01,
           6.04390115e+01, 6.79938655e+01, 7.55487196e+01, 8.31035736e+01,
           9.06584276e+01, 9.82132816e+01, 1.05768136e+02, 7.66341820e+02,
           7.80223028e+02, 7.91720180e+02, 8.01631621e+02, 8.10397510e+02],
          [1.78790041e-04, 7.52817110e+00, 1.50561634e+01, 2.25841557e+01,
           3.01121480e+01, 3.76401403e+01, 4.51681326e+01, 5.26961250e+01,
           6.02241173e+01, 6.77521096e+01, 7.52801019e+01, 8.28080942e+01,
           9.03360865e+01, 9.78640788e+01, 1.05392071e+02, 7.48896557e+02,
           7.65676936e+02, 7.78957426e+02, 7.90110053e+02, 7.99804184e+02],
          [1.78156595e-04, 7.50149910e+00, 1.50028200e+01, 2.25041410e+01,
           3.00054619e+01, 3.75067829e+01, 4.50081038e+01, 5.25094248e+01,
           6.00107457e+0

In [10]:
summary

{('CO2', 'rho'): {'is_constant': False, 'mean': None},
 ('CO2', 'mu'): {'is_constant': False, 'mean': None},
 ('CO2', 'Cp'): {'is_constant': False, 'mean': None},
 ('CO2', 'k'): {'is_constant': False, 'mean': None},
 ('CO', 'rho'): {'is_constant': False, 'mean': None},
 ('CO', 'mu'): {'is_constant': False, 'mean': None},
 ('CO', 'Cp'): {'is_constant': False, 'mean': None},
 ('CO', 'k'): {'is_constant': False, 'mean': None},
 ('O2', 'rho'): {'is_constant': False, 'mean': None},
 ('O2', 'mu'): {'is_constant': False, 'mean': None},
 ('O2', 'Cp'): {'is_constant': True, 'mean': 919.1394998004284},
 ('O2', 'k'): {'is_constant': False, 'mean': None},
 ('N2', 'rho'): {'is_constant': False, 'mean': None},
 ('N2', 'mu'): {'is_constant': True, 'mean': 1.8118992721662122e-05},
 ('N2', 'Cp'): {'is_constant': True, 'mean': 1039.82081980067},
 ('N2', 'k'): {'is_constant': False, 'mean': None}}